# Generated by Django 4.2.6 on 2023-11-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_rename_level_anticipatedresponse_level_of_understanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(blank=True, choices=[('PK', 'Pre-Kindergarten'), ('K', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6')], max_length=2, null=True),
        ),
    ]
